# Example configuration file
[settings]
nSteps = 500 # number of time steps
tStart = 0.1 # start time
tEnd = 2 # end time

[geometry]
meshName = "bay.msh"
borders = [[0.0, 0.45], [0.0, 0.2]] # define where fish are located

[IO]
logName = "log" # name of the log file created
writeFrequency = 10 # Frequency of output video. If not provided, no video is recorded.